### ISSUE TITLE
too many sign verify failed in ed25519 example 

### ISSUE THREAD

**Issue by alexSmallWorld** [getamis/alice#174]
could you take a like at this: too many sign verify failed in ed25519 example.

git repo:  https://github.com/alexSmallWorld/alice-ed25519/tree/ed25519Example 
git branch: ed25519Example
in this branch I add ed25519 example and batch test script.

how to run batch test: 1, use go 17; 2, cd example && ./rerun.sh
you will see the test processing and result.  ** false mean how many case verify sign failed. ** true mean how many case verify sign success.
like:
`/Users/walker/work/common_work/tss/gitsame/alice2/example
No matching processes belonging to you were found
singer 1
   6 false
   1 true
singer 2
   6 false
   1 true
singer 3
   6 false
   1 true`

**Comment by cychuang0924** [comment]
Hi, I spend some time checking our code. The problem arises in Round2 Line 90.
p.s = s  should be replaced by  p.s = s.Mod(s, p.curveN).
Ref: https://github.com/getamis/alice/pull/175/files
Thanks your report back!

I also add more test in EdDSA. I think that it is help to you!

**Comment by alexSmallWorld** [comment]
> Hi, I spend some time checking our code. The main problem arises in Round2 Line 90. p.s = s should be replaced by p.s = s.Mod(s, p.curveN). Ref: https://github.com/getamis/alice/pull/175/files (Merged) Thanks your report back!
> 
> I also add more test in EdDSA. I think that it is help to you!

@cychuang0924 
thank you for the bug fix. 
but I still got a little failed case in a lot of test of sign verify.
![image](https://user-images.githubusercontent.com/72785667/175882608-03a012ce-381d-462a-8a54-febf79ac5f90.png)
![image](https://user-images.githubusercontent.com/72785667/175882955-77d6ceb5-4ad1-4675-8e8a-7a55dd2c3b91.png)

you can replay this by: 1, vim rerun.sh,  use 200 instead of 20;  2 ./rerun.sh

**Comment by cychuang0924** [comment]
A method is that increasing the value of maxRetry (i.e. In Round1) to be 1000. Then you will see almost appears this problem.

**Comment by cychuang0924** [comment]
This problem arises from the Schnorr proof of siG. The original paper does not need this zero knowledge proof, so we decide to remove it. If we keep this proof, then we need to change the interface of our Library. 0In fact, you do not worry about removing it. As say the above, the original paper does not need any Schnorr proofs. After removing it, then you do not get any errors. 
Here is the fixing branch: https://github.com/getamis/alice/pull/177

**Comment by alexSmallWorld** [comment]
Thank you very much for your handling and updating of this issue. But after I merged the new code, I did a lot of testing, and there is still a small probability that the signature will fail. 

You can replay this by: 1, merge master; 2, vim rerun.sh, use 200 instead of 20; 3 ./rerun.sh
Thanks!

**Comment by cychuang0924** [comment]
I run my test 1000 time, there does not exist any failures. Cold you copy the informations of shares and the public key? 
For example, I need x-coord, rank, and shares such that I can write the tests by myself. 
Thanks!

**Comment by alexSmallWorld** [comment]
Of course, my three signer inputs are attached.
[input.zip](https://github.com/getamis/alice/files/9006587/input.zip)

By the way, I used the same input to execute the signature for 200 times, and I will fail to verify the signature once; Instead of using a different share for each signature.
Thank you for trying to solve this problem.

**Comment by cychuang0924** [comment]
Thanks for your help. I add your offering example in my test. 
See https://github.com/getamis/alice/pull/180/files
I run this test over 1000 time. There still exists any failures. This verification failure may not be caused by 
EdDSA Library. It is possible that the error is caused elsewhere.
If you have time, then you can run the tests in the ../Eddsa/frost/signer_test.go
Thank you very much!

**Comment by alexSmallWorld** [comment]
I ran the test program provided by you and did not fail.

But my testing process is different from yours. I use three independent processes to connect with each other using TCP, and then do dkg and sign for 200 times. 

You can try it on my code:
git repo: https://github.com/alexSmallWorld/alice-ed25519/tree/ed25519Example
 1, use go 17; 2, cd example && ./rerun.sh; 3, waiting for all test run out.

Thanks!

**Comment by cychuang0924** [comment]
OK! I will invite @markya0616  to help you. But, this maybe take some time.

**Comment by alexSmallWorld** [comment]
Thanks!

**Comment by alexSmallWorld** [comment]
Is there any progressing? @markya0616

**Comment by cychuang0924** [comment]
Excuse me, we release our new product in these  days,  so we have not enough time to check this problem.
